### ISSUE TITLE
Error when calculating previous epoch

### ISSUE THREAD

**Issue by CybertSys** [asnakep/poolLeaderLogs#8]
![image](https://user-images.githubusercontent.com/63478317/204163466-86907a08-e7cc-42c7-adfd-1c3c9091c8be.png)

**Comment by asnakep** [comment]
Hello,

please set: page=2 for pool history

poolHistStake = requests.get("https://cardano-mainnet.blockfrost.io/api/v0/pools/"+PoolId+"/history?page=2", headers=headers)

regards.

**Comment by CybertSys** [comment]
I do have that set.
![image](https://user-images.githubusercontent.com/63478317/204312234-14a635db-788a-4d04-b0c2-c11fbf96d731.png)

**Comment by asnakep** [comment]
Please set it to page=1

by default script comes with page=2

let me know

**Comment by CybertSys** [comment]
That worked, thank you!
